### ISSUE TITLE
Request: <label>s around <li> contents

### ISSUE THREAD

**Issue by Peeja** [github/task_list#57]
It would be a big boon to accessibility and usability if the contents of task list `<li>`s were wrapped in `<label>`s, so that the whole item was clickable.

**Comment by gma** [comment]
I've worked round this in my app with this bit of jQuery, that's bound to a click handler on the `li` elements:

```
$(event.target).closest('li').find('> input.task-list-item-checkbox').click()
```

Arguably not an ideal solution, but might be useful to somebody in the interim.

**Comment by gma** [comment]
What are your thoughts on adding labels @mtodd ? I'd also find it very helpful for styling individual tasks, and would consider doing a pull request for it if you like the idea.

**Comment by mtodd** [comment]
We originally had `<label>`s but removed them due to usability problems. For background, see https://github.com/github/task_list/issues/5 and https://github.com/github/task_list/issues/3.

To answer your question, my thoughts are that we won't add `<label>`s back to github.com which uses this library. That doesn't mean they aren't useful in *your* application. With that in mind, I'd be open to *considering* changes to optionally wrap items in `<label>`, but I won't guarantee I'll merge it.

What might be more feasible and immediate would be to subclass the `TaskList::Filter` class to override [`render_task_list_item`](https://github.com/github/task_list/blob/11050757c77ad905cbe8e0216faf01bc98174f8e/lib/task_list/filter.rb#L93-L96) to wrap the item with a `<label>`. Assuming you're using `HTML::Pipeline`, you would just swap out `TaskList::Filter` with your subclass and get the benefits immediately.

**Comment by gma** [comment]
Some interesting background info there; I hadn't considered what it would be like on mobile. Thanks for linking to the background info. I'll give it some thought – I may want to disable clicking on the text myself…

**Comment by mtodd** [comment]
Going to close this as a duplicate now!
